# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aaron Im
title: 
email: aaroncim@gmail.com
website: cowboychicken.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  cowboychicken
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: aaronim
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Aaron and I an looking for new opportunities! (to be continued)
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Economic Calendar Web Scraper and Google Calendar Updater
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  Economic Calendar Web Scraper and Google Calendar Updater
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Created a simple web scraper that fetches high-impact financial news events and adds them to a Google Calendar that users can subscribe to. Maven was used to handle dependencies such as Htmlnuit (headless browser) and the Google Cloud APIs. This project served a personal need that appeared to have no similar solutions available. 
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FlightSafety International
        link: flightsafety.com
        # link_text: flightsafety.com
        sub_title: BI&A Analyst
        caption: December 2020 - November 2021
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Build reports and dashboards that help business units gain insights and make data-driven decisions.
            Develop transformation scripts that turn raw data into more usable forms for reporting.
            Participate in regular meetings with data engineers and other analysts to groom and promote new features for enterprise analytics products.
            Work directly with senior leadership to support long-term strategic initiatives as well as urgent ad hoc requests. 
            Primarily using PowerBI and Azure database products. 
      - layout: left
        title: FlightSafety International
        link: flightsafety.com
        # link_text: flightsafety.com
        sub_title: BI&A Analyst
        caption: December 2020 - November 2021
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Build re
      - layout: left
        title: FlightSafety International
        link: flightsafety.com
        # link_text: flightsafety.com
        sub_title: | 
            Business Analyst
            Application Administrator (Starting Position)
        caption: March 2017 - December 2020
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Sole administrator and point of contact for SAAS product used to deploy company's customer survey that is sent to over 50k customers each year.
            Developed new applications and maintained existing ones using the aforementioned SAAS product. This required basic scripting (JScript) and HMTL/CSS.
            Collaborate with internal stakeholders and draft requirement documents.
            Streamlined a business process that was previously handled manually and un-trackable. Reduced administration time and allowed reduction of headcount.
      - layout: left
        title: Jones-Blair Industrial Coatings
        link: flightsafety.com
        # link_text: flightsafety.com
        sub_title: Chemist
        caption: January 2015 - August 2016
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Part of the resin polymer R&D team for an industrial coatings company. Held a variety of responsibilities that supported various stages of product development and manufacturing.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Texas at Dallas
        caption: Graduated 2019
        sub_title: BS Software Engineering
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        #description: | # this will include new lines to allow paragraphs
        #  During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
        #
        #  I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      - layout: left
        title: University of Texas at San Antonio
        caption: Graduated 2014
        sub_title: BS Chemistry
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my other interests and hobbies are:
      - Working on my cars and taking them to the track
      - Trading futures
      - Playing the drums
    #  Look at this cool image  
    #  ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag