# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aaron Im
title: 
email: aaroncim@gmail.com
website: cowboychicken.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  cowboychicken
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: aaronim
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: my resume
  icon: far fa-file
  url: https://drive.google.com/file/d/1etKwdKOHIVC6TS93tmsRylUJuLsGiZjY/view?usp=share_link
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Aaron and I am looking for new opportunities! 
  (to be continued)
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Economic Calendar Web Scraper and Google Calendar Updater
        link: https://github.com/cowboychicken/Economic-Google-Calendar
        # link_text: Project Website
        additional_links:
          - title:  Economic Google Calendar
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Java, Maven, Google Calendar and OAuth APIs
        description: | # this will include new lines to allow paragraphs
          Created a simple web scraper that fetches high-impact financial news events and adds them to a Google Calendar that users can subscribe to.
          Maven was used to handle dependencies such as Htmlunit (headless browser) and the Google Cloud APIs.
          Several Economic Calendar APIs exist but require a monthly fee. Thus the web scraping route was chosen.
          This project served a personal need that appeared to have no similar solutions available. Day traders should always check for economic news events as they can create higher than usual volatility. By leveraging Google Calendar, which I already use quite frequently, the seamless integration into my day has proven to be quite beneficial. I also have the ability to easily share this with other traders. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FlightSafety International
        link: flightsafety.com
        # link_text: flightsafety.com
        sub_title: | 
          Business Intelligence Analyst
          Business Analyst
          Application Administrator
        caption: March 2017 - November 2021
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Started as an administrator for Operations. Became the primary developer and point of contact for a SAAS product. Eventually joined the corporate BI team as an analyst to focus more on data analytics and developing reports to help Operations make more data driven decisions. Primarily using PowerBI and Azure database products.
          
          Collaborate with stakeholders from various business units to draft requirements for reports/dashboards built with Power BI and applications that needed to be built with the aforementioned SAAS product.
          Participate in regular meetings with engineers, developers and other analysts to groom and promote new features for various enterprise analytics products.
          Work directly with senior leadership to support long-term strategic initiatives as well as urgent ad hoc requests.
          Developed new applications and maintained existing ones that were built using the aforementioned SAAS product. Entails basic scripting with JScript and HMTL/CSS.
          Built applications that streamlined several business processes in Operations that were previously handled manually and not standardized. Significantly reducing administration time and increasing the ability to track and analyze.
      - layout: left
        title: Jones-Blair Industrial Coatings
        link: jones-blair.com
        # link_text: jones-blair.com
        sub_title: |
          
          Chemist
        caption: January 2015 - August 2016
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Part of the R&D team that supported various stages of product development and manufacturing for an industrial coatings company. Focused on developing new and existing resin polymers that were used throughout their formulations.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Texas at Dallas
        caption: Graduated 2019
        sub_title: BS Software Engineering
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        #description: | # this will include new lines to allow paragraphs
        #  During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
        #
        #  I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      - layout: left
        title: University of Texas at San Antonio
        caption: Graduated 2014
        sub_title: BS Chemistry
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my other interests and hobbies are:
      - Working on my cars and taking them to the track
      - Trading futures
      - Playing the drums
    #  Look at this cool image  
    #  ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
